name: AI PR Writer

on:
  pull_request:
    # Trigger when opened, when code changes (synchronize), OR when you edit the text!
    types: [opened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gemini Action
        uses: ./
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

          action_type: >-
            ${{ 
              (contains(github.event.pull_request.body, '!review') || 
               contains(github.event.pull_request.title, '!review')) 
              && 'review' || 'description' 
            }}

      - name: Post Comment to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file pr_description.md
